page.tsx:200 Error fetching sales transactions for dashboard: FirebaseError: Missing or insufficient permissions.
dashboard:1 The resource https://6000-firebase-studio-1748521735942.cluster-nzwlpk54dvagsxetkvxzbvsl….dev/_next/static/media/or3nQ6H_1_WfwkMZI_qYFrcdmhHkjko-s.p.be19f591.woff2 was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
dashboard:1 The resource https://6000-firebase-studio-1748521735942.cluster-nzwlpk54dvagsxetkvxzbvsl…tations.dev/_next/static/media/gyByhwUxId8gMEwcGFWNOITd-s.p.da1ebef7.woff2 was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.