FirebaseError: The query requires an index. You can create it here: https://console.firebase.google.com/v1/r/project/imss-gutguru/firestore/indexes?create_composite=ClZwcm9qZWN0cy9pbXNzLWd1dGd1cnUvZGF0YWJhc2VzLyhkZWZhdWx0KS9jb2xsZWN0aW9uR3JvdXBzL3NhbGVzVHJhbnNhY3Rpb25zL2luZGV4ZXMvXxABGgoKBnNpdGVJZBABGhMKD3RyYW5zYWN0aW9uRGF0ZRACGg0KCWlzRGVsZXRlZBACGgwKCF9fbmFtZV9fEAI . The query contains range and inequality filters on multiple fields, please refer to the documentation for index selection best practices: https://cloud.google.com/firestore/docs/query-data/multiple-range-fields.