WebSocket connection to 'wss://6000-firebase-studio-1748521735942.cluster-nzwlpk54dvagsxetkvxzbvslyi.cloudworkstations.dev/_next/webpack-hmr' failed: (anonymous) @ use-websocket.ts:16 react-stack-bottom-frame @ react-dom-client.development.js:24035 runWithFiberInDEV @ react-dom-client.development.js:1510 commitHookEffectListMount @ react-dom-client.development.js:10514 commitHookPassiveMountEffects @ react-dom-client.development.js:10635 commitPassiveMountOnFiber @ react-dom-client.development.js:12441 recursivelyTraversePassiveMountEffects @ react-dom-client.development.js:12415 commitPassiveMountOnFiber @ react-dom-client.development.js:12557 recursivelyTraversePassiveMountEffects @ react-dom-client.development.js:12415 commitPassiveMountOnFiber @ react-dom-client.development.js:12557 recursivelyTraversePassiveMountEffects @ react-dom-client.development.js:12415 commitPassiveMountOnFiber @ react-dom-client.development.js:12557 recursivelyTraversePassiveMountEffects @ react-dom-client.development.js:12415 commitPassiveMountOnFiber @ react-dom-client.development.js:12557 recursivelyTraversePassiveMountEffects @ react-dom-client.development.js:12415 commitPassiveMountOnFiber @ react-dom-client.development.js:12557 recursivelyTraversePassiveMountEffects @ react-dom-client.development.js:12415 commitPassiveMountOnFiber @ react-dom-client.development.js:12557 recursivelyTraversePassiveMountEffects @ react-dom-client.development.js:12415 commitPassiveMountOnFiber @ react-dom-client.development.js:12434 recursivelyTraversePassiveMountEffects @ react-dom-client.development.js:12415 commitPassiveMountOnFiber @ react-dom-client.development.js:12444 recursivelyTraversePassiveMountEffects @ react-dom-client.development.js:12415 commitPassiveMountOnFiber @ react-dom-client.development.js:12434 recursivelyTraversePassiveMountEffects @ react-dom-client.development.js:12415 commitPassiveMountOnFiber @ react-dom-client.development.js:12434 recursivelyTraversePassiveMountEffects @ react-dom-client.development.js:12415 commitPassiveMountOnFiber @ react-dom-client.development.js:12557 recursivelyTraversePassiveMountEffects @ react-dom-client.development.js:12415 commitPassiveMountOnFiber @ react-dom-client.development.js:12434 recursivelyTraversePassiveMountEffects @ react-dom-client.development.js:12415 commitPassiveMountOnFiber @ react-dom-client.development.js:12434 recursivelyTraversePassiveMountEffects @ react-dom-client.development.js:12415 commitPassiveMountOnFiber @ react-dom-client.development.js:12557 recursivelyTraversePassiveMountEffects @ react-dom-client.development.js:12415 commitPassiveMountOnFiber @ react-dom-client.development.js:12557 recursivelyTraversePassiveMountEffects @ react-dom-client.development.js:12415 commitPassiveMountOnFiber @ react-dom-client.development.js:12453 flushPassiveEffects @ react-dom-client.development.js:15795 flushPendingEffects @ react-dom-client.development.js:15760 performSyncWorkOnRoot @ react-dom-client.development.js:16286 flushSyncWorkAcrossRoots_impl @ react-dom-client.development.js:16137 flushSpawnedWork @ react-dom-client.development.js:15664 commitRoot @ react-dom-client.development.js:15390 commitRootWhenReady @ react-dom-client.development.js:14643 performWorkOnRoot @ react-dom-client.development.js:14566 performWorkOnRootViaSchedulerTask @ react-dom-client.development.js:16274 performWorkUntilDeadline @ scheduler.development.js:45Understand this error page.tsx:244 Error updating profile: FirebaseError: Missing or insufficient permissions. error @ intercept-console-error.ts:41 onSubmit @ page.tsx:244 await in onSubmit (anonymous) @ createFormControl.ts:1195 await in (anonymous) executeDispatch @ react-dom-client.development.js:16426 runWithFiberInDEV @ react-dom-client.development.js:1510 processDispatchQueue @ react-dom-client.development.js:16476 (anonymous) @ react-dom-client.development.js:17074 batchedUpdates$1 @ react-dom-client.development.js:3253 dispatchEventForPluginEventSystem @ react-dom-client.development.js:16630 dispatchEvent @ react-dom-client.development.js:20716 dispatchDiscreteEvent @ react-dom-client.development.js:20684Understand this error page.tsx:221
           POST https://firestore.googleapis.com/google.firestore.v1.Firestore/Write/channel?VER=8&database=projects%2Fimss-gutguru%2Fdatabases%2F(default)&gsessionid=b-dnW81SM_fDqKfDU8O9AAvycKNlyKFKXA9qi5EaAl8&SID=vYeIqRxIluGEmEFcnje3oQ&RID=53778&TYPE=terminate&zx=v8fgddgew3wz 400 (Bad Request)