use-websocket.ts:16 WebSocket connection to 'wss://6000-firebase-studio-1748521735942.cluster-nzwlpk54dvagsxetkvxzbvslyi.cloudworkstations.dev/_next/webpack-hmr' failed: (anonymous) @ use-websocket.ts:16Understand this error intercept-console-error.ts:41 Error updating stock: FirebaseError: Firestore transactions require all reads to be executed before all writes.