Failed to load resource: the server responded with a status of 403 ()Understand this error or3nQ6H_1_WfwkMZI_qYFrcdmhHkjko-s.p.be19f591.woff2:1
           Failed to load resource: the server responded with a status of 403 ()Understand this error
gyByhwUxId8gMEwSGFWNOITddY4-s.81df3a5b.woff2:1

           Failed to load resource: the server responded with a status of 403 ()Understand this error
use-websocket.ts:16 WebSocket connection to 'wss://6000-firebase-studio-1748521735942.cluster-nzwlpk54dvagsxetkvxzbvslyi.cloudworkstations.dev/_next/webpack-hmr' failed:
(anonymous) @ use-websocket.ts:16Understand this error
ItemsClientPage.tsx:199 Ignored call to 'prompt()'. The document is sandboxed, and the 'allow-modals' keyword is not set.
callGoogleSheetsApiForItemActions @ ItemsClientPage.tsx:199Understand this error
intercept-console-error.ts:41 Error saving item: FirebaseError: Missing or insufficient permissions.
error @ intercept-console-error.ts:41Understand this error
firestore.googleapis.com/google.firestore.v1.Firestore/Write/channel?VER=8&database=projects%2Fimss-gutguru%2Fdatabases%2F(default)&gsessionid=MMUuLbeN0davTgQICFvKVpNlYOCT7mitXnpT_IaSHMM&SID=dy8JVu1DX6CPkzrAeYEUPw&RID=34852&TYPE=terminate&zx=ybaq10qpazvv:1

           Failed to load resource: the server responded with a status of 400 ()Understand this error
2

         Chrome is moving towards a new experience that allows users to choose to browse without third-party cookies.